### ISSUE TITLE
거북목 각도 (CA) 를 알아내는 방법

### ISSUE THREAD

**Issue by ssubnia** [frredy99/Mechatronics#1]
theta 로부터 CA를 구할 수 있는 방법이 있을까요..?

<img width="502" alt="image" src="https://github.com/frredy99/Mechatronics/assets/146702859/4baad1de-c993-49e2-8148-6cad241a9abe">

**Comment by ssubnia** [comment]
..

**Comment by frredy99** [comment]
저도 처음 코드를 작성할 때 CA를 구하는 방법을 고민을 많이 했습니다.
하지만 목 뒷부분(C7)의 좌표가 주어지지 않으면 CA를 계산할 수 없다는 결론을 얻었습니다.
아쉽지만 CA대신 theta로 FHP를 판단해야 할 것 같습니다.

혹시라도 theta로부터 CA를 계산할 수 있는 방법을 찾게 되면 알려주세요.
